version: "3.7"
services:
  phpfpm:
    image: php:7.4-fpm
    volumes:
      - ./phpfpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.22.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - phpfpm

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  telegraf:
    # image: telegraf:1.9.1
    image: telegraf:1.23.2
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./telegraf/env.telegraf
    depends_on:
      - influxdb
      - influxdb_v2
      - nginx
      - elasticsearch
      - mongo
      - nodejs
      - grafana

  influxdb:
    image: influxdb:1.8

  influxdb_v2:
    # image: influxdb:2.0
    image: influxdb:2.3.0
    ports:
      - "8086:8086"
    env_file:
      - ./influxdb_v2/env.influxdb_v2

  mongo:
    # image: mongo:4.4.4
    image: mongo:5.0.9
    expose:
      - 27017

  elasticsearch:
    # image: elasticsearch:7.11.2
    image: elasticsearch:8.3.2
    expose:
      - 9200
    ports:
      - "19200:19200"
    environment:
      discovery.type: single-node

  nodejs:
    build: ./nodejs
    ports:
      - "1337:1337"
      - "9615:9615"
